# Generated by Django 2.2.6 on 2019-10-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20191019_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='DOB',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='emergency_contact_phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_condition',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
